name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Add utils to PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/utils" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          pytest --browser ${{ matrix.browser }} --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
